# -*- makefile -*-

# Using native tools (e.g., on X86 Linux)
#TOOLPREFIX = /usr/local/i386elfgcc/bin/i386-elf-
# Cross-compiling (e.g., on Mac OS X)
#TOOLPREFIX=i386-jos-elf-

CC = $(TOOLPREFIX)gcc
AS = $(TOOLPREFIX)gas
LD = $(TOOLPREFIX)ld

AR = $(TOOLPREFIX)ar

OBJCOPY = $(TOOLPREFIX)objcopy
OBJDUMP = $(TOOLPREFIX)objdump

# to compile regular programs (e.g., mkfs)
# apparently on old linux I need to add -m32 otherwise
# I get some errors when running mkfs
NATIVEGCC=gcc -m32



# original cflags
CFLAGS = -fno-builtin -nostdinc -fno-stack-protector \
          -Wall  -m32

# in rev7:
#-fno-pic -static -fno-builtin -fno-strict-aliasing -Wall -MD -ggdb -m32 -Werror -fno-omit-frame-pointer -fno-stack-protector -fno-pic

#-ggdb

ASFLAGS = -m32
# pad: funk add -static, not sure why
LDFLAGS = -static -m elf_i386
#-MD
